# Generated by Django 6.0.3 on 2026-03-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medics', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отслеживаемый параметр',
                'verbose_name_plural': 'Отслеживаемые параметры',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата анкетирования')),
                ('optional', models.TextField(blank=True, verbose_name='Комментарий пациента')),
                ('result', models.IntegerField(default=0, verbose_name='Результат оценки')),
                ('status', models.CharField(choices=[('sent_to_patient', 'Отправлена пациенту'), ('sent_to_medic', 'Отправлена врачу'), ('answered', 'Принята'), ('denied', 'Отклонена')], default='sent_to_patient', max_length=20, verbose_name='Статус')),
                ('medics_respond', models.TextField(blank=True, verbose_name='Комментарий врача')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='medics.medic')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='patients.medicalcard')),
                ('parameters', models.ManyToManyField(related_name='questionnaires', to='questionnaires.monitoredparameter', verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PatientResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=255, verbose_name='Ответ')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.monitoredparameter', verbose_name='Параметр')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_responses', to='questionnaires.questionnaire')),
            ],
            options={
                'verbose_name': 'Ответ пациента',
                'verbose_name_plural': 'Ответы пациентов',
                'unique_together': {('questionnaire', 'parameter')},
            },
        ),
    ]
