# Generated by Django 6.0.3 on 2026-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специальность')),
                ('education', models.TextField(verbose_name='Образование')),
                ('work_place', models.CharField(max_length=200, verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
    ]
