# Generated by Django 6.0.3 on 2026-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время приёма')),
                ('symptoms', models.TextField(verbose_name='Симптомы')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('tests', models.TextField(blank=True, verbose_name='Анализы')),
                ('treatment', models.TextField(verbose_name='Лечение')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Приём',
                'verbose_name_plural': 'Приёмы',
                'ordering': ['-date'],
            },
        ),
    ]
