# Generated by Django 6.0.3 on 2026-03-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('medics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointment',
            name='medic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='medics.medic'),
        ),
    ]
